E

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -29,27 +29,26 @@ jobs:
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python ${{matrix.pyversion}}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{matrix.pyversion}}
-    - name: psycopg2 prerequisites
-      run: sudo apt-get install libpq-dev
-    - name: Install dependencies and config
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-        cp decide/local_settings.gactions.py decide/local_settings.py
-    - name: Run tests
-      id: test
-      run: |
-        cd decide
-        coverage run --branch --source=. ./manage.py test booth -v 2 --keepdb 
-        echo "::set-output name=tests_failed::$(echo $?)"
-      id: set-tests-output
-      continue-on-error: true
-
-    - name: Set tests output
+      - uses: actions/checkout@v3
+      - name: Set up Python ${{matrix.pyversion}}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{matrix.pyversion}}
+      - name: psycopg2 prerequisites
+        run: sudo apt-get install libpq-dev
+      - name: Install dependencies and config
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          cp decide/local_settings.gactions.py decide/local_settings.py
+      - name: Run tests
+        id: test
+        run: |
+          cd decide
+          coverage run --branch --source=. ./manage.py test booth -v 2 --keepdb 
+          echo "::set-output name=tests_failed::$(echo $?)"
+        id: set-tests-output
+        continue-on-error: true
+      - name: Set tests output
         if: ${{ always() }}
         run: echo "::set-output name=tests_failed::${{ steps.set-tests-output.outputs.tests_failed }}"
